#!/usr/bin/env bash

DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DIR"

if [[ -n $(type php 2> /dev/null) ]]; then
	PHP_BINARY=$(type -p php)
else
	echo "Couldn't find a PHP binary in system PATH"
	exit 1
fi

if [ -f ./src/ArchLoader.php ]; then
	LAUNCH_FILE="./src/ArchLoader.php"
else
	echo "Launch file not found."
	exit 1
fi

set +e
exec "$PHP_BINARY" "$LAUNCH_FILE"